<h2 class="text-center" style="margin-top: 5px; padding-top: 0;">Войдите в чат</h2>
<hr>
<?php
use App\lib\Helpers;
Helpers::get_alert();
?>

<div class="row join-room">
	<div class="col-md-6 col-md-offset-3 mx-auto">

		<form id="join-room-frm" role="form" method="POST" action="login" class="form-horizontal">
			<!-- CSRF -->
			<input type="hidden" name="token" value="<?= $_COOKIE['PHPSESSID']; ?>">
			<div class="form-group">

				<div class="form-group mt-3">
					<div class="input-group">
						<input type="email" class="form-control" id="email" name="email" placeholder="Введите Email" value="">
					</div>
				</div>

				<div class="form-group mt-3">
					<div class="input-group">
						<input type="password" class="form-control" id="password" name="password" placeholder="Введите пароль" value="">
					</div>
				</div>

				<div class="form-group mt-3">
					<input type="submit" value="Вход" class="btn btn-success btn-block" id="join" name="join">
				</div>

				<div class="form-group">
					<p class="text-center mt-3">или пройдите регистрацию: </p>
					<p class="text-center"><a class="btn btn-link" href="register">Регистрация</a></p>
				</div>
		</form>
	</div>
</div>