<h2 class="h2 text-center my-2"><?= $title; ?></h2>
<hr>

<?php
use App\lib\Helpers;
Helpers::get_alert();
?>

<div class="row join-room">
    <div class="col-md-6 col-md-offset-3 mx-auto">
        
    <form id="join-room-frm" role="form" method="post" action="register" class="form-horizontal">
            <!-- CSRF -->
            <input type="hidden" name="token" value='<?= $_COOKIE['PHPSESSID']; ?>'>
                <div class="form-group mt-3">                
                <div class="input-group">
                    <input type="email" class="form-control" id="email" name="email" placeholder="Введите Email" value="">
                </div>
                </div>
            
                <div class="form-group mt-3">
                <div class="input-group">
                    <input type="password" class="form-control" id="password" name="password" placeholder="Введите пароль" value="">
                </div>
                </div>

                <div class="form-group mt-3">
                    <input type="submit" value="Регистрация" class="btn btn-warning btn-block" id="join" name="join">
                </div>

                <div class="form-group">
                    <p class="text-center mt-3">или, если зарегистрированы: </p>
                    <p class="text-center"><a class="btn btn-link" href="login">Вход</a></p>
                </div>
    </form>
    </div>
</div>